title: Elias Ramírez | SEO Técnico
email: elias@kaderank.com
description: >-
  SEO técnico, análisis de indexación, rastreo, rendimiento y optimización web para empresas y emprendedores.
logo: /assets/img/logo.png
theme: jekyll-theme-minimal
show_downloads: false
lang: es
url: "https://eliasmr-code.github.io/Technical-SEO/"

